spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root : info
    com.briup.hblog: debug
  file:
    name: log/blog-dev.log
#开发环境下端口
server:
  port: 8089